server:
  port: 7000
spring:
  application:
    name: api-gateway

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.35.187:8848

    gateway:
      routes: # 路由数组[路由 就是指定当请求满足什么条件的时候转到哪个微服务]
        - id: product_route #当前路由的标识，要求唯一
#          uri: http://localhost:8081 #请求要转发的地址,手动指定
          uri: lb://service-product # lb指的是从nacos中按照名称获取微服务,并遵循负载均衡策略
          order: 1 #路由的优先级，数字越小级别越高
          predicates: #断言（就是路由转发要满足的条件）
            - Path= /product-serv/** # 当请求路径满足Path指定的规则时,才进行路由转发 ,默认微服务实例名称
          filters: # 过滤器,请求在传递过程中可以通过过滤器对其进行一定的修改
            - StripPrefix=1 #转发之前去掉一层路径


